soup_to_bits/config/routes.rb
Rails.application.routes.draw do
  resources :categories, :soups
  
  root to: "categories#index"
  
  get "/allcategories" => redirect("/")
  
  get "/soups/:id/toggle_featured", to: "soups#toggle_featured", as: :toggle_featured
  get "/secret_soups", to: "soups#secret_soups"

end

soup_to_bits/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :soups
end

soup_to_bits/app/models/soup.rb
class Soup < ActiveRecord::Base
  belongs_to :category
  
  validates :name, presence: true, uniqueness: true
end

soup_to_bits/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
  end
end

soup_to_bits/app/controllers/soups_controller.rb
class SoupsController < ApplicationController
  before_action :fetch_soup, only: [:show, :edit, :update, :destroy, :toggle_featured]

  def show
    respond_to do |format|
      format.html
      format.json {render json: @soup}
    end
  end
  
  def index
    @soups = Soup.all
    
    respond_to do |format|
      format.json {render json: @soups}
    end
  end
  
  def new
    
  end
  
  def edit
  
  end
  
  def udpate
    
  end
  
  def destroy
    
  end
  
  def fetch_soup
    @soup = Soup.find(params[:id])
  end
  
  def toggle_featured
    @soup.toggle!(:featured)
    flash[:notice] = "Successfully changed the featured flag."
    redirect_to @soup
  end
  
  def secret_soups
    session[:vip] = true 
    redirect_to root_path
  end
end

soup_to_bits/app/helpers/categories_helper.rb
module CategoriesHelper
end

soup_to_bits/app/helpers/soups_helper.rb
module SoupsHelper
end

soup_to_bits/app/views/categories/index.html.erb
<h1>Soup Categories</h1>
<ul>
    <% @categories.each do |category|%>
        <li><%= link_to category.name, category %> (<%= category.soups.count %>)</li>
    <%end%>
    
    <%if session[:vip] = true%>
        <p>Secret Soups</p>
    <%end%>
</ul>

soup_to_bits/app/views/categories/show.html.erb
<h1><%= @category.name %> </h1>
<ul>
    <% @category.soups.each do |soup|%>
        <li><%= link_to soup.name, soup %> </li>
    <% end %>
    
    <p><%= link_to "Back to Soup Categories", categories_path %></p>
    
</ul>    

soup_to_bits/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoupToBits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice]%>
<p><%= flash[:notice]%></p>
<% end %>
<%= yield %>

</body>
</html>

soup_to_bits/app/views/soups/index.html.erb
haha

soup_to_bits/app/views/soups/show.html.erb
<h1><%= @soup.name %></h1>
<% if @soup.featured? %>
    <p>This delicious soup is featured this month. </p>
<% else %>
    <p>This soup is not in seacon, so it's not great right now </p>
<% end %>
<%if params[:admin] == "true"%>
<p><%= link_to "toggle featured", toggle_featured_path(@soup)%></p>
<%end%>